---
- name: Pull docker image of devops-integration
  hosts: all
  tasks:
    - name: Pull devops-integration devops image
      docker_image:
        name: abhisek1906/devops-integration
        source: pull

    - name: running container
      shell: docker run -it -d abhisek1906/devops-integration /bin/bash